DROP TABLE INTERVENTION CASCADE CONSTRAINTS;
DROP TABLE MATERIEL CASCADE CONSTRAINTS;
DROP TABLE TECHNICIEN CASCADE CONSTRAINTS;
DROP TABLE CATEGORIE CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CATEGORIE;
DROP SEQUENCE SEQ_TECHNICIEN;
DROP SEQUENCE SEQ_MATERIEL;
DROP SEQUENCE SEQ_INTERVENTION;

CREATE SEQUENCE SEQ_CATEGORIE    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TECHNICIEN   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MATERIEL     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INTERVENTION START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE CATEGORIE (
    ID_CATEGORIE  NUMBER(10)    NOT NULL,
    LIBELLE       VARCHAR2(100) NOT NULL,
    DESCRIPTION   VARCHAR2(255),
    CONSTRAINT PK_CATEGORIE PRIMARY KEY (ID_CATEGORIE),
    CONSTRAINT UQ_CATEGORIE_LIBELLE UNIQUE (LIBELLE)
);

CREATE TABLE TECHNICIEN (
    ID_TECHNICIEN NUMBER(10)    NOT NULL,
    NOM           VARCHAR2(100) NOT NULL,
    PRENOM        VARCHAR2(100) NOT NULL,
    SPECIALITE    VARCHAR2(100),
    CONSTRAINT PK_TECHNICIEN PRIMARY KEY (ID_TECHNICIEN)
);

CREATE TABLE MATERIEL (
    ID_MATERIEL   NUMBER(10)    NOT NULL,
    REFERENCE     VARCHAR2(50)  NOT NULL,
    DESIGNATION   VARCHAR2(200) NOT NULL,
    DATE_ACHAT    DATE          NOT NULL,
    ETAT          VARCHAR2(30)  DEFAULT 'En service' NOT NULL,
    ID_CATEGORIE  NUMBER(10)    NOT NULL,
    CONSTRAINT PK_MATERIEL PRIMARY KEY (ID_MATERIEL),
    CONSTRAINT UQ_MATERIEL_REF UNIQUE (REFERENCE),
    CONSTRAINT FK_MAT_CATEGORIE FOREIGN KEY (ID_CATEGORIE)
        REFERENCES CATEGORIE(ID_CATEGORIE),
    CONSTRAINT CHK_ETAT CHECK (ETAT IN ('En service','En reparation','Declasse'))
);

CREATE TABLE INTERVENTION (
    ID_INTERVENTION   NUMBER(10)    NOT NULL,
    DATE_INTERVENTION DATE          NOT NULL,
    DESCRIPTION       VARCHAR2(500) NOT NULL,
    ID_MATERIEL       NUMBER(10)    NOT NULL,
    ID_TECHNICIEN     NUMBER(10)    NOT NULL,
    CONSTRAINT PK_INTERVENTION PRIMARY KEY (ID_INTERVENTION),
    CONSTRAINT FK_INT_MATERIEL   FOREIGN KEY (ID_MATERIEL)
        REFERENCES MATERIEL(ID_MATERIEL),
    CONSTRAINT FK_INT_TECHNICIEN FOREIGN KEY (ID_TECHNICIEN)
        REFERENCES TECHNICIEN(ID_TECHNICIEN)
);

SELECT 'Tables creees avec succes !' AS STATUT FROM DUAL;